### ISSUE TITLE
插件安装后es启动失败

### ISSUE THREAD

**Issue by jeetom** [pengcong90/elasticsearch-analysis-hanlp#15]
-Djava.security.policy=F:/soft/servers/elasticsearch-6.2.4/plugins/analysis-hanlp/plugin-security.policy
这里设置相对路径会出现无权限的问题，换成绝对路径后没有出现无权限问题
GET /_analyze 
{ 
"analyzer":"hanlp-index",
"text":"三只松鼠"
}
结果是504
{
  "statusCode": 504,
  "error": "Gateway Time-out",
  "message": "Client request timeout"
}

应该怎么设置呢？ 操作系统是win10   jdk1.8

**Comment by alittlebitcool** [comment]
linux添加了就有权限错误，不添加就用不了怎么办啊
