### ISSUE TITLE
按照README的做法有报错

### ISSUE THREAD

**Issue by HuskyDoge** [pengcong90/elasticsearch-analysis-hanlp#3]
SEVERE: 没有找到HanLP.properties，可能会导致找不到data

**Comment by pengcong90** [comment]
在什么系统下部署的？最好控制台解下图，我看一下，我这边window和mac测试都通过了

**Comment by HuskyDoge** [comment]
linux, 我现在用了hanlp-ext的这个项目的插件，当时可能是因为没有修改elasticsearch.in.sh里面的环境变量导致的。
