### ISSUE TITLE
照着README去做报错了

### ISSUE THREAD

**Issue by bungder** [pengcong90/elasticsearch-analysis-hanlp#9]
![image](https://user-images.githubusercontent.com/3251115/42078040-984284ba-7bad-11e8-8ee8-c162c15ca22d.png)
![image](https://user-images.githubusercontent.com/3251115/42078354-b5cfcafa-7bae-11e8-8617-6ab75485b531.png)

系统是LinuxMint：
![image](https://user-images.githubusercontent.com/3251115/42078091-c62feaf2-7bad-11e8-8441-3099b43ea056.png)
hanlp的配置文件也按照README改了：
![image](https://user-images.githubusercontent.com/3251115/42078121-e143e50a-7bad-11e8-9c9c-d91b1fde7f3b.png)
这里也c尝试过将root后面加上data，CoreDictionaryPath本来没改的，后来报错了就改为绝对路径，报错信息也是一样。

es的版本是5.2.2

**Comment by pengcong90** [comment]
怎么启动的elasticsearch服务？在哪个路径下启动的？

**Comment by pengcong90** [comment]
可以先把hanlp的字典拷贝到elasticsearch/bin目录下

**Comment by bungder** [comment]
这个应该是HanLP的问题，hanlp加载hanlp.properties的方式是classloader.getResourceAsStream，我直接跑HanLP的代码也是加载不了，应该是hanlp启动的时候cp参数的问题

**Comment by bungder** [comment]
就是HanLP的问题，classloader.getResourceAsStream方法加载自己jar包内的资源是可以的，但是加载外部资源的话，javadoc并没有明确的规则说明，所以我修改了HanLP的代码，重新打包，替换掉plugin里面的hanlp的jar包就可以了
